### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by DrobenyukA** [IgorPopach/js-lessons#3]
https://github.com/IgorPopach/js-lessons/blob/10f6a903e91ab4cbf0b162009a3b7ff22424f91d/React/lesson_5/src/components/content/content.js#L59

What is ` this.info` ???
Maybe it should be `e`

**Comment by IgorPopach** [comment]
When compiling with "onClick={this.handleSelectedImage(info)}" I get an error:

"Failed to compile
./src/components/content/content.js
  Line 59:  'info' is not defined  no-undef

Search for the keywords to learn more about each error."
